# Archivo de configuración para el análisis de SonarQube del frontend

# La clave del proyecto debe ser la misma que configuraste en los secretos de GitHub
sonar.projectKey=${env:SONAR_PROJECT_KEY}

# Nombre y versión del proyecto que aparecerán en SonarCloud
sonar.projectName=Ticke-T Frontend
sonar.projectVersion=1.0

# Ruta al código fuente relativo a la carpeta 'app'
sonar.sources=src

# Codificación de los archivos
sonar.sourceEncoding=UTF-8

# Opcional: Rutas a los archivos de prueba para un análisis diferenciado
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js,**/*.spec.js,**/*.spec.jsx